apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      app: ingress
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: ingress
        version: v1
    spec:
      containers:
      - name: ingress
        image: ingress:1.0
        ports:
        - containerPort: 80